### DISCUSSION TITLE
Moving to the Jekyll format - now it's much easier to add events to the site

### DISCUSSION THREAD

**Discussion by NHLOCAL** [NHLOCAL/AiTimeline#7] [Announcements]
## We moved the site to the Jekyll structure. Now you can add events to the timeline very easily - pay attention to the following instructions!

1. **Fork the Repository:** Fork this repository to your GitHub account.

2. **Add or Update Events:**
    * Open the `_data/timeline.yml` file.
    * Add new events following this structure:

       ```yaml
       - year: 2024 # The year of the event
         events:
           - date: July # Date format: Month
             info:
               - text: "**New Amazing AI Model Released!**" # Event description (use **bold** for emphasis).
               - text: "More details about the release."
                 special: true # Add `special: true` to highlight events
       ```

    * You can also add new links in `_data/links.yml` using a similar structure.
